services:
  backup:
    container_name: equal-risk-backup
    image: offen/docker-volume-backup:v2
    environment:
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
      BACKUP_CRON_EXPRESSION: "0 */6 * * *"
    volumes:
      - pgdata-prod:/backup/equal-risk-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/backups:/archive

  postgres:
    container_name: equal-risk-postgres
    image: postgres:17
    ports:
      - 5432:5432
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${EQUAL_RISK_PORTFOLIO_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${EQUAL_RISK_PORTFOLIO_DATABASE_PASSWORD}
      POSTGRES_DB: ${EQUAL_RISK_PORTFOLIO_DATABASE}
    volumes:
      - pgdata-prod:/var/lib/postgresql/data

volumes:
  pgdata-prod:
    name: equal-risk-portfolio-pgdata-prod
    external: true

networks:
  default:
    external: true
    name: proxy
